spring.application.name=FMOnitor-WebBE

spring.datasource.url=jdbc:postgresql://my-fmo-db.cn2gks2o2jit.ap-southeast-2.rds.amazonaws.com:5432/FMOnitor-aws-rds-db?sslmode=require
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update