spring.application.name=FMOnitor-WebBE

spring.datasource.url=jdbc:postgresql://my-fmo-db.cn2gks2o2jit.ap-southeast-2.rds.amazonaws.com:5432/FMOnitor-aws-rds-db?sslmode=require
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.security.oauth2.client.registration.google.client-id=590989370337-0thql0io9tfgi3vvk1rhqj9bn1rirhun.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

app.jwt.secret=${JWT_SECRET:uRZthNqwDsftXLfRznIlf4ClXttUvDCNkRHmniBRg6Q=}
app.jwt.expiration-ms=3600000

spring.jpa.hibernate.ddl-auto=update